name: urbit-king
version: 0.10.1
license: MIT
license-file: LICENSE

library:
  source-dirs: lib
  ghc-options:
    - -fwarn-incomplete-patterns
    - -fwarn-unused-binds
    - -fwarn-unused-imports
    - -Werror
    - -O2

tests:
  urbit-king-tests:
    source-dirs: test
    main: Main.hs
    dependencies: urbit-king
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

dependencies:
  - aeson
  - ansi-terminal
  - async
  - base
  - base-unicode-symbols
  - binary
  - bytestring
  - case-insensitive
  - classy-prelude
  - conduit
  - containers
  - cryptohash-sha256
  - cryptohash-sha512
  - data-default
  - data-fix
  - directory
  - ed25519
  - entropy
  - exceptions
  - extra
  - filepath
  - fixed-vector
  - flat
  - ghc-prim
  - Glob
  - hashable
  - hashtables
  - http-client
  - http-client-tls
  - http-types
  - integer-gmp
  - iproute
  - largeword
  - lens
  - lmdb-static
  - lock-file
  - megaparsec
  - memory
  - mtl
  - multimap
  - murmur3
  - network
  - optparse-applicative
  - para
  - pretty-show
  - primitive
  - process
  - QuickCheck
  - random
  - regex-tdfa
  - regex-tdfa-text
  - resourcet
  - rio
  - semigroups
  - smallcheck
  - stm
  - stm-chans
  - tasty
  - tasty-golden
  - tasty-hunit
  - tasty-quickcheck
  - tasty-th
  - template-haskell
  - terminal-progress-bar
  - terminal-size
  - text
  - these
  - time
  - transformers
  - unix
  - unliftio
  - unliftio-core
  - unordered-containers
  - urbit-atom
  - urbit-azimuth
  - urbit-hob
  - utf8-string
  - vector
  - wai
  - wai-conduit
  - wai-websockets
  - warp
  - warp-tls
  - web3
  - websockets

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MagicHash
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - NumericUnderscores
  - OverloadedStrings
  - PackageImports
  - PartialTypeSignatures
  - PatternSynonyms
  - QuasiQuotes
  - Rank2Types
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UnboxedTuples
  - UnicodeSyntax
  - ViewPatterns

executables:
  urbit-king:
    main: Main.hs
    source-dirs: app
    dependencies:
      - urbit-king
    ghc-options:
      - -threaded
      - -rtsopts
      - -static
      - -O2
      - "-with-rtsopts=-N"
      - -fwarn-incomplete-patterns
