#!/usr/bin/env bash

set -ex

cd pkg/interface/chat
npm install
gulp bundle-prod &
cd ../launch
npm install
gulp bundle-prod &
cd ../clock
npm install
gulp bundle-prod &
cd ../publish
npm install
gulp bundle-prod &
cd ../soto
npm install
gulp bundle-prod &
cd ../weather
npm install
gulp bundle-prod

set +x
