#!/usr/bin/env bash

set -ex

cd pkg/landscape/chat
npm install
gulp bundle_prod &
cd ../launch
npm install
gulp bundle_prod &
cd ../clock
npm install
gulp bundle_prod &
cd ../publish
npm install
gulp bundle_prod &
cd ../soto
npm install
gulp bundle_prod &
cd ../weather
npm install
gulp bundle_prod

set +x
