#!/usr/bin/env bash

set -ex

if [ "$TRAVIS_PULL_REQUEST" = false ]
then

    sh/test --arg debug false

else

    nix-build nix/ops       \
              -A test       \
              -A brass      \
              --max-jobs 2  \
              --no-out-link

    sh/test --arg debug true
    sh/update-brass-pill

fi
