#!/usr/bin/env bash

set -ex

STACK_YAML="`pwd`/pkg/hs/stack.yaml"

stack test king --fast

if [ "$TRAVIS_PULL_REQUEST" = false ]
then

    sh/test --arg debug false

else

    sh/test --arg debug true

fi
