#!/usr/bin/env bash

set -ex

export STACK_YAML="`pwd`/pkg/hs/stack.yaml"

stack test urbit-king

if [ "$TRAVIS_PULL_REQUEST" = false ]
then

    sh/test --arg debug false

else

    sh/test --arg debug true

fi
