#!/usr/bin/env bash

# Usage: create-ropsten-pills

# Build the ivory and brass ropsten pills, copying them to the local directory,
# named with the current give revision

set -xeuo pipefail

cd "${0%/*}/.."

rev="$(git rev-parse HEAD)"
sha="${rev:0:5}"

brass="brass-ropsten-${sha}.pill"
ivory="ivory-ropsten-${sha}.pill"

cp -f "$(nix-build -A brass-ropsten.build --no-out-link)" "$brass"
cp -f "$(nix-build -A ivory-ropsten.build --no-out-link)" "$ivory"

chmod 0644 "$brass" "$ivory"
