#!/usr/bin/env bash

set -e

sha=$(git rev-parse $(git branch --show-current))

brass=$(nix-build nix/ops -A brass-ropsten --no-out-link)
ivory=$(nix-build nix/ops -A ivory-ropsten --no-out-link)

cp $brass ./brass-ropsten-${sha:0:5}.pill
cp $ivory ./ivory-ropsten-${sha:0:5}.pill
