#!/usr/bin/env bash

set -e

case $# in
  0) target=./fakezod;;
  1) target=$1;;
  *) echo "Usage: $0 [target]" >&2
     exit 1;;
esac

if [ -e "$target" ]
then echo "Target directory '$target' already exists." >&2
     exit 1
fi

pkg=$(nix-build nix/ops -A fakezod --no-out-link)

mkdir -p "$(dirname "$target")"
cp -L -r $pkg/ $target
chmod -R u+rw $target
