#!/usr/bin/env bash

set -ex

STACK_YAML="`pwd`/pkg/hs/stack.yaml"

if [ -n "${TRAVIS_TAG-}" ]
then
  ver="$TRAVIS_TAG"
elif [ -n "${TRAVIS_COMMIT-}" ]
then
  ver="$TRAVIS_COMMIT"
else
  ver="$(git rev-parse HEAD)"
fi

mkdir -p release

pushd pkg/hs

king=$(bash $(nix-build --no-link -A fullBuildScript))

popd

cp "$king"/bin/king "release/king-linux64-$ver"

for plat in linux64 darwin
do
  sh/cross urbit "$plat"

  echo "packaging release/urbit-$plat-$ver.tgz"
  (cd cross/$plat; tar cz .) > release/urbit-$plat-$ver.tgz
done
