blank_issues_enabled: true
contact_links:
  - name: Submit a Landscape issue
    url: https://github.com/tloncorp/landscape-apps/issues/new/choose
    about: Issues with Landscape should be filed at tloncorp/landscape-apps. This includes Groups, Talk, and Landscape proper.
  - name: urbit-dev mailing list
    url: https://groups.google.com/a/urbit.org/g/dev
    about: Developer questions and discussions also take place on the urbit-dev mailing list.
