#!/usr/bin/env bash

# generated by janeway v0.11.2
#
# shellcheck disable=SC2039,SC2034,SC1091

set -e
set -o pipefail

GIT=/nix/store/04msdwxh4p5m6546yri5zz0naw9k50s2-git-2.25.1/bin/git
SED=/nix/store/v1pa6217x3yi6gms06y6xqnc48dayqb4-gnused-4.8/bin/sed
NPM=/nix/store/r9wicz3s5p3wlhqajshryj8bjzgz5js8-node_npm-6.14.4/bin/npm
GSUTIL=/nix/store/m7l44y46jn97xcmmcf399zjbn2sw30zm-google-cloud-sdk-286.0.0/bin/gsutil
GCLOUD=/nix/store/m7l44y46jn97xcmmcf399zjbn2sw30zm-google-cloud-sdk-286.0.0/bin/gcloud
HUB=/nix/store/7ay8l2wd015drvfia0sp1b5hgafjkvg6-hub-2.14.2-bin/bin/hub
MSMTP=/nix/store/9pf7mydaccrnmwr16rb89qv99b4c1awy-msmtp-1.8.7/bin/msmtp

if [[ ! $(type -P $GIT) ]]; then
  echo "ERROR: git not found"
  exit 1
else
  :
fi

if [[ ! $(type -P $SED) ]]; then
  echo "ERROR: sed not found"
  exit 1
else
  :
fi

if [[ ! $(type -P $HUB) ]]; then
  echo "ERROR: hub not found"
  exit 1
else
  :
fi

if [[ ! $(type -P $GSUTIL) ]]; then
  echo "ERROR: gsutil not found"
  exit 1
else
  :
fi

if [[ ! $(type -P $GCLOUD) ]]; then
  echo "ERROR: gcloud not found"
  exit 1
else
  :
fi

if [[ ! $(type -P $NPM) ]]; then
  echo "ERROR: npm not found"
  exit 1
else
  :
fi

janeway() {
  set -e
  set -o pipefail
  if [[ ! -d pkg/interface ]]; then
    echo "ERROR: pkg/interface not found"
    exit 1
  else
    pushd pkg/interface
    $NPM install && $NPM run build:prod
    popd
  fi
  if [ ! -f bin/solid.pill ]; then
    echo "ERROR: bin/solid.pill not found"
    exit 1
  else
    SIZE=$(du -k bin/solid.pill | cut -f1)
    if [ "$SIZE" -lt 10 ]; then
      echo "ERROR: bin/solid.pill appears to be an LFS pointer"
      exit 1
    else
      urbit -dF zod -B bin/solid.pill -A pkg/arvo -c fakezod-jw
    fi
  fi
  herb fakezod-jw -p glob -d +glob/make
  
  GLOBPATH=$(ls fakezod-jw/.urb/put/*.glob)
  GLOBFILE=${GLOBPATH##*/}
  GLOBBASE=${GLOBFILE%%.glob}
  GLOBHASH=${GLOBBASE##glob-}
  JSPATH=$(ls pkg/arvo/app/landscape/js/bundle/index.*.js)
  JSFILE=${JSPATH##*/}
  
  $SED --in-place "4s/.*/++  hash  $GLOBHASH/" pkg/arvo/app/glob.hoon
  
  herb fakezod-jw -p hood -d '+hood/mount /=home='
  cp pkg/arvo/app/glob.hoon fakezod-jw/home/app/glob.hoon
  rm -f fakezod-jw/home/app/landscape/js/bundle/$JSFILE
  $SED -E --in-place "s/index\.(js|([a-z]|[0-9])*\.js)/$JSFILE/" pkg/arvo/app/landscape/index.html
  cp pkg/arvo/app/landscape/index.html fakezod-jw/home/app/landscape/index.html
  herb fakezod-jw -p hood -d '+hood/commit %home'
  
  if [ ! -f "$GLOBPATH" ]; then
    echo "ERROR: $GLOBPATH not found"
    exit 1
  else
    $GSUTIL cp "$GLOBPATH" gs://bootstrap.urbit.org/"$GLOBFILE"
  fi
  herb fakezod-jw -P solid.pill -d '+solid'
  mv -f solid.pill ./bin/solid.pill
  if [ -e fakezod-jw/.vere.lock ]; then
    kill -3 "$(< fakezod-jw/.vere.lock)"
    while kill -0 "$(< fakezod-jw/.vere.lock)" &> /dev/null; do
      sleep 1
    done
    rm -rf fakezod-jw
  else
    rm -rf fakezod-jw
  fi
  $GIT add pkg/arvo/app/glob.hoon
  $GIT add bin/solid.pill
  $GIT commit -m "glob: update to $GLOBHASH"
}
export -f janeway

cat << EOF
will perform the following actions:

  BUILD_LANDSCAPE
  BOOT_FAKEZOD @ HEAD
  CREATE_GLOB
  UPLOAD_GLOB
  CREATE_PILL (solid)
  KILL_FAKEZOD
  MAKE_GLOB_COMMIT
  DONE

EOF

read -p "proceed with actions? (y/n)" -n 1 -r <&1
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
  janeway
else
  :
fi
