#!/usr/bin/env bash
set -euo pipefail

function xxd()
{
  cch=0
  echo "unsigned char $2[] = {"
  while IFS='' read line
  do
    for i in $line
    do
      echo -n " 0x$i,"
      cch=$((cch+1))
    done
    echo
  done < <(od -An -v -tx1 $1)
  echo "};"
  echo "unsigned int $2_len = $cch;"
}

case $(uname -s|tr A-Z a-z) in
  *mingw64*)
  ;;
  *)
    echo This script works only on MingW64.
    exit 1
  ;;
esac

if [ ! -e config.mk ]
then
  # ensure required mingw packages are installed
  mpkgs=(cmake curl gcc jq libsigsegv libuv make wslay)
  pacman -S --needed autoconf automake-wrapper libtool patch ${mpkgs[@]/#/mingw-w64-x86_64-}

  unset cdirs
  unset ldirs
  declare -a cdirs
  declare -a ldirs
  . <(jq -sr '
add|to_entries|.[]|select(.value.mingw)|.key as $key|(if .value.url then "
mkdir -p ../\($key)
pushd ../\($key)
curl -L \(.value.url)|(tar --strip \(.value.mingw.strip+1) -xzf - || true)" +
("../urbit/compat/mingw/\($key).patch"|"
[ -e \(.) ] && patch -p 1 <\(.)") else "
pushd ../\($key)" end) + "
\(.value.mingw.prepare//"")
make \(.value.mingw.make//"")
popd
\(.value.mingw.include//"."|if type == "array" then .[] else . end|"cdirs+=(-I../\($key)/\(.))
")\(.value.mingw.lib//"."|if type == "array" then .[] else . end|"ldirs+=(-L../\($key)/\(.))
")"' ../../nix/sources.json ../../nix/sources-mingw.json)

  xxd /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt include_ca_bundle_crt >include/ca-bundle.h
  xxd ../../bin/ivory.pill u3_Ivory_pill >include/ivory.h

  CFLAGS="${CFLAGS-} ${cdirs[@]}" LDFLAGS="${LDFLAGS-} ${ldirs[@]}" PKG_CONFIG=echo ./configure
fi

make build/urbit build/urbit-worker
