name: urbit-atom
version: 0.10.1
license: MIT
license-file: LICENSE

ghc-options:
  - -Wall
  - -Werror
  - -Wno-type-defaults
  - -Wno-unused-matches
  - -Wno-name-shadowing
  - -Wno-unbanged-strict-patterns
  - -O2

library:
  source-dirs: lib
  dependencies:
    - base
    - bytestring
    - ghc-prim
    - integer-gmp
    - primitive
    - text
    - vector

tests:
  urbit-atom-tests:
    source-dirs: test
    main: Main.hs
    ghc-options: "-threaded -rtsopts -with-rtsopts=-N"
    dependencies:
      - base
      - bytestring
      - QuickCheck
      - text
      - urbit-atom
      - vector

benchmarks:
  urbit-atom-bench:
    source-dirs: bench
    main: Main.hs
    ghc-options: "-threaded -rtsopts -with-rtsopts=-N"
    dependencies:
      - base
      - bytestring
      - criterion
      - urbit-atom

default-extensions:
  - ApplicativeDo
  - BangPatterns
  - BlockArguments
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MagicHash
  - MultiParamTypeClasses
  - NamedFieldPuns
  - NoImplicitPrelude
  - NumericUnderscores
  - OverloadedStrings
  - PackageImports
  - PartialTypeSignatures
  - PatternSynonyms
  - QuasiQuotes
  - Rank2Types
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UnboxedTuples
  - UnicodeSyntax
  - ViewPatterns
