{-# LANGUAGE StrictData #-}

module Urbit.Vere.Serf.IPC.Types where

import Urbit.Prelude hiding ((<|))
import Urbit.Arvo                   (Ev, FX, Seed)
import Urbit.Vere.Serf.Types

-- Private data structures for Urbit.Vere.Serf.IPC, but made StrictData without
-- making the rest of Urbit.Vere.Serf.IPC strict.

data Vent
  = VFake Ship
  | VDawn Seed
  deriving (Show)

data Boot = Boot
  { bPill :: (Atom, Maybe Ev)  -- XX maybe clay event for (unimplemented) `-A`?
  , bVent :: Vent
  -- | For future flexibility, currently unused.
  , bMore :: [Ev]
  }
  deriving (Show)

data Live
  = LMeld ()
  | LPack ()
  deriving (Show)

data Sync
  = SCram ()
  | SSave ()
  deriving (Show)

data Task
  -- | %live: lifecycle management
  --
  -- currently only |meld and |pack. failure is fatal to the process,
  -- success is acknowledged with an in-order [%live ~] response.
  = TLive Live
  -- | %exit: graceful/clean exit
  --
  -- no response is given, exit code will be zero on success
  | TExit ()
  -- | %peek: read from the namespace
  --
  -- `mil` is milliseconds to time out the read,
  -- response is in-order, successful result or crash report
  | TPeek Atom Gang ScryReq
  -- | %poke: process an event
  --
  -- `mil` is milliseconds to time out the read,
  -- the payload is a raw ovum ([wire card]), no timestamp.
  -- response is in-order, successful effects, or some number of crash reports.
  -- event replacement is transparent and unobservable unless it fails,
  -- in which case it can be inferred from the number of crash reports.
  | TPoke Atom Ev
  -- | %sync: synchronization request
  --
  -- request that a snapshot be taken (%save).
  -- the response can be out-of-order, as mars is free
  -- to take snapshots at its discretion.
  -- %cram is questionable, and may be removed.
  | TSync Sync
  deriving (Show)

data Gift
  -- | %live: lifecycle mgmt task acknowledgement
  = GLive ()
  -- | %flog: single line of logging output, produced directly by mars
  --
  -- generated by printf() or friends, may contain escape sequences,
  -- may be sent at any time.
  | GFlog Cord
  -- | %slog: single line of logging output, produced by arvo
  -- 
  -- may be sent at any time.
  | GSlog Slog
  -- | %peek: %peek task response
  | GPeek (Each (Maybe (Term, Noun)) Goof)
  -- | %poke: %poke task response
  | GPoke (Each FX [Goof])
  -- | %ripe: initial status message on restart (not boot)
  --
  -- includes protocol version number, kelvin versions (wynn),
  -- pier identity and fake bit, and current synchronization state.
  -- will only be sent once, on restart, after any necessary replay.
  -- (structure implies that version negototiation has already been completed)
  -- (sync state could be factored out into a %sync gift)
  | GRipe Ripe
  -- %sync: synchronization notification
  -- 
  -- mars has saved a new snapshot at event N, with kernel mug M.
  -- may be sent at any time, with or without a preceding %sync task.
  | GSync Atom Atom
  deriving (Show)

deriveNoun ''Vent
deriveNoun ''Boot
deriveNoun ''Live
deriveNoun ''Sync
deriveNoun ''Task
deriveNoun ''Gift
