name: Push to master

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/feature.yml'
      - '.github/workflows/develop.yml'
      - '.github/workflows/release.yml'
      - '.github/workflows/master.yml'
      - '.github/workflows/shared.yml'
      - 'pkg/arvo/**'
      - 'pkg/docker-image/**'
      - 'pkg/ent/**'
      - 'pkg/ge-additions/**'
      - 'pkg/libaes_siv/**'
      - 'pkg/urbit/**'
      - 'pkg/urcrypt/**'
      - 'tests/**'
      - 'bin/**'
      - 'nix/**'
      - 'default.nix'

jobs:
  call-vere:
    uses: ./.github/workflows/shared.yml
    with:
      pace: 'live'
      upload: >-
        ${{
        (github.ref_name == 'next/vere' && github.ref_type == 'branch')
        }}
    secrets: inherit
